CREATE TABLE tb_publishers (

   id UUID PRIMARY KEY,
   name VARCHAR(100) NOT NULL UNIQUE,

   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);