CREATE TABLE tb_authors (
    id UUID PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);